comm_config:
  mqtt:
    type: client
    client_name: workstation
    mqtt_broker: localhost
    mqtt_broker_port: 1884
    mqtt_sub_timeout_s: 30
    mqtt_server_topic: advert_server
    mqtt_client_topic: advert_client
    heartbeat_timeout_s: 15
  grpc:
    workers: 8
    sync_port: 50053
    async_port: 50054
dataset_config:
  datasets_dir_path: /home/fedml/flotilla_final/fedml-ng/src/data
general_config:
  temp_dir_path: temp
  cleanup_session_on_exit: False
  cleanup_model_cache_on_exit: False
  cleanup_temp_on_exit: False
  use_gpu: True
