comm_config:
  mqtt:
    type: server
    mqtt_broker: localhost
    mqtt_broker_port: 1884
    mqtt_sub_timeout_s: 1
    mqtt_server_topic: advert_server
    mqtt_client_topic: advert_client
    mqtt_heartbeat_interval_s: 5
    num_heartbeats_timestamp_cached: 5
    max_heartbeat_miss_threshold: 5
  grpc:
    max_message_length: 1048576000 # (1000*1024*1024)
    chunk_size_bytes: 1024
    timeout_s: 1200000
  restful:
    rest_hostname: 0.0.0.0
    rest_port: 12345
state:
  state_location: redis
  state_hostname: localhost
  state_port: 6379
checkpoint_dir_path: ./checkpoint
validation_data_dir_path: ./val_data
temp_dir_path: ./scratch
