comm_config:
  mqtt:
    type: server
    mqtt_broker: localhost
    mqtt_broker_port: 1883
    mqtt_sub_timeout_s: 10
    mqtt_server_topic: advert_server
    mqtt_client_topic: advert_client
    mqtt_heartbeat_interval_s: 5
    num_heartbeats_timestamp_cached: 5
    max_heartbeat_miss_threshold: 3
  grpc:
    max_message_length: 1048576000 # (1000*1024*1024)
    chunk_size_bytes: 1024
    timeout_s: 600
  restful:
    rest_hostname: 0.0.0.0
    rest_port: 12345
state:
  state_location: inmemory
  state_hostname: null
  state_port: null
checkpoint_dir_path: ./checkpoints
validation_data_dir_path: src/val_data
temp_dir_path: ./scratch
