session_config:
  session_id: dev
  use_gpu: True
  aggregator: fedavg
  aggregator_args: None
  client_selection: fedavg
  client_selection_args:
    client_fraction: 1
  checkpoint_interval: 5
  generate_plots: False

benchmark_config:
  model_id: LeNet5
  model_dir: ./models/LeNet5
  model_class: LeNet5_class
  dataset: EMNIST_IID
  bench_minibatch_count: 500
  batch_size: 16
  learning_rate: 0.001
  timeout_duration_s: 120

server_training_config:
  model_dir: ./models/LeNet5
  global_model_validation_batch_size: 100
  num_training_rounds: 50

client_training_config:
  model_id: LeNet5
  model_class: LeNet5_class
  epochs: 1
  dataset: EMNIST_IID
  batch_size: 16
  learning_rate: 0.001
  train_timeout_duration_s: 300
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True

model_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10
