session_config:
  session_id: mobilenet_fedavg_cifar10
  use_gpu: False
  aggregator: fedavg
  aggregator_args: None
  client_selection: fedavg
  client_selection_args:
    client_fraction: 1
  checkpoint_interval: 10
  validation_round_interval: 1
  generate_plots: True

benchmark_config:
  skip_benchmark: True
  model_id: MobileNet
  model_dir: ../models/MobileNet
  model_class: MobileNet_class
  dataset: CIFAR10_IID
  batch_size: 32
  learning_rate: 0.001
  bench_minibatch_count: 10
  timeout_duration_s: 180

server_training_config:
  model_dir: ../models/MobileNet
  validation_dataset: CIFAR10_IID
  global_model_validation_batch_size: 32
  num_training_rounds: 20
  global_timeout_duration_s: 3600

client_training_config:
  model_id: MobileNet
  model_class: MobileNet_class
  dataset: CIFAR10_IID
  epochs: 3
  batch_size: 32
  learning_rate: 0.001
  train_timeout_duration_s: 300
  loss_function: crossentropy
  loss_function_custom: False
  optimizer: adam
  optimizer_custom: False

model_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10
