comm_config:
  mqtt:
    type: server
    mqtt_broker: 10.24.24.31
    mqtt_broker_port: 1884
    mqtt_sub_timeout_s: 30
    mqtt_server_topic: advert_server
    mqtt_client_topic: advert_client
  grpc:
    chunk_size_bytes: 1024
    timeout_s: 14400
temp_dir_path: ./server_temp
