session_config:
  session_id: session-1
  aggregator: None
  client_selection: random_subset
  percentage_client_selection: 100.0
  save_metrics_to_file: True

benchmark_config:
  bench_model_id: AlexNet
  bench_model_dir: ./models/AlexNet
  bench_model_class: AlexNet
  bench_minibatch_count: 100
  bench_batch_size: 100
  learning_rate: 0.001
  bench_timeout_duration_s: 10
train_config:
  model_id: AlexNet
  model_dir: ./models/AlexNet
  model_class: AlexNet
  num_training_rounds: 3
  epochs: 3
  batch_size: 16
  learning_rate: 0.001
  train_timeout_duration_s: 300
  validation_data_path: ./data/MNIST/test.pth
  validation_batch_size: 100
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True
