model_details:
  model_id: LeNet5
  model_class: LeNet5_class
  model_tags: [CNN]
  suitable_datasets: [MNIST, FMNIST]

default_training_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10
